Tela Perfil
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Mobile pull request #10
Opened 2022-04-01 19:23 UTC by PauloAbiAcl

# Descrição
Desenvolvido a interface da Tela Perfil

# Está concertando alguma issue aberta ?
#165

# Tarefas realizadas
- Criação da tela.
- Componentização do botão da tela.
- Correção da responsividade da tela de selecionar tipo de cadastro.

# Observações 
- O Botão de editar e excluir ainda não tem função, portanto atribuir como função a eles a mesma do botão sair.
- Deixei os campos de informação com valores fictícios, pois não sei quais valores eles vão receber.

2022-04-04 18:40 UTC, Denniel-sudo reviewed
Ficou muito bom, cara!! Só fazer os ajustes de padronização que está tudo certo!

2022-04-04 18:40 UTC, Denniel-sudo commented on lib/components/icon_text_button.dart
> +    this.textColor = const Color(0XFF03045E),
Tem um arquivo colors.dart no global que serve para caso precisar de alguma cor, se n tive lá pode adicionar lá só para manter o padrão de import das cores e ter um controle melhor pq ela pode ser reutilizada por lá ao invés de instanciar novamente.

2022-04-04 18:40 UTC, Denniel-sudo commented on lib/components/icon_text_button.dart
> +    this.splashColor = const Color(0XFF00B4D8),
O mesmo para essa tbm

2022-04-04 18:40 UTC, Denniel-sudo commented on lib/pages/select_account/select_account.dart
> +                  Icons.agriculture,
Eu n lembro se teve alteração quanto a imagem do botão com o protótipo, caso tiver tido pode desconsiderar este comentário.

2022-04-04 18:40 UTC, Denniel-sudo commented on lib/pages/profile/profile_page.dart
> +              Color(0XFF0077B6),
A mesma padronização para esse arquivo quanto as cores

2022-04-04 18:41 UTC, Denniel-sudo requested changes
Só fazer os ajustes de padronização que está tudo certo!

2022-04-05 17:23 UTC, brenno-silva approved these changes
Tudo certo, bom trabalho!

2022-04-05 17:28 UTC, Denniel-sudo approved these changes
Ficou muito bom! Parabéns!

2022-04-05 17:37 UTC, merged