Tela de Pendências
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Mobile pull request #12
Opened 2022-04-04 00:29 UTC by brenno-silva

# Descrição
Criação da tela pendências e modal de analisar agrotóxico

# Está concertando alguma issue aberta ?
[#159](https://github.com/UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs/issues/159)

# Tarefas realizadas
- Criação da tela
- Criação do modal
- Criação da model de PesticideAplicationModel

2022-04-04 21:37 UTC, VitorLamego requested changes
Parabéns pelo trabalho. Deixei comentado apenas algumas divergências em relação ao protótipo e algumas sugestões de código.

2022-04-04 21:37 UTC, VitorLamego commented on lib/pages/pendencies/pendencies.dart
> +        child: Center(
Não precisa desse Center

2022-04-04 21:37 UTC, VitorLamego commented on lib/pages/pendencies/components/pesticide_card.dart
> +                    style: Utils.estateTextStyle,
Acho que seria interessante ter um estilo diferente para esse titulo do card. Seria necessário alterar no protótipo.

2022-04-04 21:37 UTC, VitorLamego commented on lib/pages/pendencies/components/pesticide_card.dart
> +                ),
Essas informações estão diferentes do protótipo, mas acredito que todas fazem sentido. Só alterar o protótipo para manter fiel ao app. Acredito que seja importante colocar de qual produtor é determinada solicitação, para que o técnico consiga identificar quem está aplicando, assim como está no protótipo.

2022-04-04 21:37 UTC, VitorLamego commented on lib/pages/pendencies/components/pesticide_analysis.dart
> +                  widget.pesticide.dosage.toString() + " ml",
Essa informação sempre vai chegar em ml ? Somente certificar isso daí.

2022-04-04 21:37 UTC, VitorLamego commented on lib/controllers/pesticide_analysis/pesticide_analysis_controller.dart
> +  }
Método não utilizado. Futuramente será utilizado para alguma funcionalidade ?

2022-04-04 21:37 UTC, VitorLamego commented on lib/pages/pendencies/components/pesticide_analysis.dart
> +            // ignore: avoid_print
Remover comentário.

2022-04-04 22:43 UTC, brenno-silva commented on lib/controllers/pesticide_analysis/pesticide_analysis_controller.dart
> +  }
Será utilizado para realizar a conexão com a service futuramente

2022-04-06 13:41 UTC, PauloAbiAcl approved these changes
Bom trabalho!!

2022-04-07 00:27 UTC, VitorLamego approved these changes
Bom trabalho!

2022-04-07 00:27 UTC, merged