177 Tela Editar Propriedade
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Mobile pull request #15
Opened 2022-04-10 19:16 UTC by brenno-silva

# Descrição
Criação da tela de Editar propriedade

# Está concertando alguma issue aberta ?
[#177](https://github.com/UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs/issues/177)

# Tarefas realizadas
- Edição do protótipo
- Criação da tela

2022-04-17 19:21 UTC, CarlosFiuza requested changes
Na tela de edição é possível editar o campo de cidade e estado, mas percebi que na patch request enviada a api não contêm o campo cidade e estado

2022-04-17 19:46 UTC, Denniel-sudo requested changes
Quando eu altero as informações da propriedade, ao clicar em editar novamente ele não está com as informações atualizadas em cima da alteração que eu fiz, acho q atualizar as informações da model propriedade assim que der sucesso na requisição pode ajudar nisso.

2022-04-18 00:47 UTC, CarlosFiuza approved these changes
Bom trabalho!

2022-04-18 03:09 UTC, Denniel-sudo approved these changes
Muito bom!

2022-04-18 03:10 UTC, merged