#178 Adicionando requisiçao a home do tecnico e ajustando componentes…
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Mobile pull request #16
Opened 2022-04-11 01:56 UTC by CarlosFiuza

## Descrição
Adição de requisição a tela home do produtor

## Está concertando alguma issue aberta ?
[#178](https://github.com/UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs/issues/178)

## Tarefas realizadas
- Adição da requisição
- Mudança no componente TopBarArrowBack para evitar que técnico edite propriedade
- Mudança na PropriedadeModel para evitar que tecnico adicione plantação, marque como colhida e adicione agrotoxico em plantios

2022-04-12 18:22 UTC, brenno-silva requested changes
Excelente, só um detalhe no nome de uma função

2022-04-12 18:22 UTC, brenno-silva commented on lib/models/PropriedadeModel.dart
> +  Tuple2<List<TalhaoModel>, List<TalhaoModel>> getPlotsActive({
Trocar `getPlotsActive` para `getPlots` já que está retornando todos

2022-04-13 15:42 UTC, PauloAbiAcl approved these changes
Bom trabalho, tudo certo!!

2022-04-13 16:51 UTC, brenno-silva approved these changes

2022-04-13 16:52 UTC, merged