Adicionar Plantação
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Mobile pull request #17
Opened 2022-04-11 02:18 UTC by VitorLamego

Foi desenvolvida a dialog de adicionar plantação.
Algumas alterações foram necessárias para que funcionasse da maneira correta:

- Propagar a info de Propriedade entre alguns componentes
- Da forma que desenvolveram a tela de propriedade a requisição das infos não era feita toda vez que a página era buildada, portanto foi necessário adicionar à lógica de adição de plantio essa requisição para atualizar a página de propriedades.

Observações:
- O back não deixa mandar outra data além do dia atual
- O back ainda não aceita imagem
- Já que o back não possui endpoint para o get de cultura, é necessário criar uma cultura a cada adição

2022-04-11 20:09 UTC, CarlosFiuza approved these changes
Bom trabalho!
Ficou muito bom.

2022-04-18 00:39 UTC, brenno-silva requested changes
Ficou muito bom, só dois detalhes: as imagens na tela de propriedade não estão carregando e um condicional abaixo que acredito que seja o inverso.

2022-04-18 00:39 UTC, brenno-silva commented on lib/controllers/add_plantation/add_plantation_controller.dart
> +    if (culturas.isEmpty) return;
Trocar pelo isNotEmpty

2022-04-18 01:08 UTC, VitorLamego commented
@brenno-silva a imagem de propriedade não está relacionada com essa task. A de cultura foi trocada porque interferia diretamente nas requisições que iriam ser feitas, precisando das models atualizadas para evitar retrabalho, mas a parte de propriedade não é de responsabilidade dessa task.

2022-04-18 01:40 UTC, brenno-silva approved these changes

2022-04-18 01:40 UTC, merged