Integrar pendências
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Mobile pull request #21
Opened 2022-04-14 23:30 UTC by brenno-silva

# Descrição
Fazer a ligação das telas de pendências com o backend

# Está concertando alguma issue aberta ?
[#184](https://github.com/UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs/issues/184)

# Tarefas realizadas
- Integração com o backend
- Readequação da tela e componentes

2022-04-17 19:30 UTC, CarlosFiuza requested changes

2022-04-17 19:30 UTC, CarlosFiuza commented on lib/pages/pendencies/components/pesticide_analysis.dart
> +                        style: Utils.estateTextStyle,
Porque foi colocado o ID do agrotóxico?

2022-04-17 21:56 UTC, PauloAbiAcl approved these changes
Parabéns, tirando o questionamento do Carlos, tudo ok.

2022-04-18 00:43 UTC, brenno-silva commented on lib/pages/pendencies/components/pesticide_analysis.dart
> +                        style: Utils.estateTextStyle,
Para o técnico ter uma base do que o produtor inseriu como agrotóxico

2022-04-18 00:49 UTC, CarlosFiuza approved these changes
Muito bom!

2022-04-18 01:15 UTC, merged