Tela Login
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Mobile pull request #3
Opened 2022-03-13 18:32 UTC by VitorLamego

# Descrição
Foi desenvolvido a interface de login da aplicação assim como a integração dessa tela com o backend do app. 

# Está concertando alguma issue aberta ?
#111

# Tarefas realizadas
- Criação da tela de login
- Integração com o backend

# Observações 
- A classe "Home" foi criada apenas para teste, sendo alterado posteriormente quando as duas telas estiverem prontas
- O botão de "Cadastro" ainda não tem navegação pelo fato da tela de selecionar tipo de conta não estar pronta
- Para teste do login deve ser alterado em Utils.utils.dart o ipLocal para o ip da sua máquina

2022-03-15 11:14 UTC, CarlosFiuza requested changes

2022-03-15 11:14 UTC, CarlosFiuza commented on lib/pages/login/login_page.dart
> +                    ),
Seria interessante adicionar um Form como widget pai desses dois textFields para conseguir fazer uma validação ao clicar no botão "entrar", assim o app não faria uma requisição com os campos vazios por exemplo.

2022-03-15 22:01 UTC, oEduardoAfonso reviewed
Eu concordo com as mudanças propostas pelo Carlos, o widget Form facilita bastante as validações dos campos.

Os outros detalhes eu acredito que não faz sentido solicitar mudanças na sua branch já que não temos nenhum padrão definido e que com os demais PR's a gente vai padronizando aos poucos.

Ótimo trabalho Lamego, e assim que as alterações forem feitas eu deixo minha aprovação no PR.

2022-03-16 16:59 UTC, CarlosFiuza approved these changes
Vi que adicionou os validators, agora ta ótimo!
Quanto ao testes acredito que ainda não seja necessário realizar testes de todas as telas ainda, então pra não falhar a pipeline apenas um teste simples da main, por exemplo, poderia resolver os erros gerados.

2022-03-17 01:28 UTC, oEduardoAfonso requested changes
A validação com o TextFormField e o login funcionaram perfeitamente, só encontrei uma pequena parte do código que me deixou confuso, acredito que tenha seja um erro.

2022-03-17 01:28 UTC, oEduardoAfonso commented on lib/pages/login/login_page.dart
> +      if (!failedLogin) if (!failedLogin) navigateToHome();
Não entendi o motivo desses 2 if's seguidos

2022-03-17 20:01 UTC, oEduardoAfonso approved these changes
Boa, ótimo trabalho Lamego!!

2022-03-17 20:02 UTC, merged