Tela Home Produtor e Home Técnico
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Mobile pull request #4
Opened 2022-03-14 23:28 UTC by PauloAbiAcl

# Descrição
Desenvolvido a interface Home produtor e Home Técnico

# Está concertando alguma issue aberta ?
#112 e #113

# Tarefas realizadas
- Criação das telas
- Controle de dados

# Observações 
- O Estate Card e Pendency Card ainda usam valores fictícios, pois ainda não é possível trazer esses dados do back-end.

2022-03-17 17:16 UTC, CarlosFiuza approved these changes
Show de bola galerinha, muito bom!

2022-03-18 20:57 UTC, VitorLamego commented on lib/components/Topbar/topbar.dart
> +import 'package:flutter/material.dart';
Comentário relacionado a estruturação dos arquivos dentro da pasta components. Não precisa criar uma pasta para cada arquivo criado. O interessante é deixar aqueles componentes que forem globais na pasta raíz "components" e os componentes específicos de cada página dentro de uma pasta com o nome da tela e não do componente.

2022-03-18 21:07 UTC, VitorLamego commented on lib/components/Topbar/topbar.dart
> +        ),
A área de clique do botão de perfil está absurdamente grande com esse padding de 30px, sugiro que coloquem o padding como 0, já que o IconButton tem um padding padrão, e adicionem um margin a partir de um Container para esse IconButton.
```suggestion
Container(
    margin: EdgeInsets.only(right: 20),
     child: IconButton(
          icon: const Icon(Icons.person),
          iconSize: 50,
          color: Colors.white,
          padding: EdgeInsets.all(0),
          // ignore: no-empty-block
          onPressed: () {},
        ),
  ),
```

2022-03-18 21:11 UTC, VitorLamego commented on lib/components/Topbar/topbar.dart
> +        IconButton(
Alterem as cores do splashColor e highlightColor para alguma cor da paleta de cores do projeto, esse cinza em cima do azul ficou um pouco estranho.

2022-03-18 21:16 UTC, VitorLamego commented on lib/components/EstateCard/estate_card.dart
> +      child: Center(
Center não está afetando em nada aqui.

2022-03-18 21:20 UTC, VitorLamego commented on lib/components/EstateCard/estate_card.dart
> +            child: Row(
Utilizaram duas Rows dentro de uma Row, o que não afeta em nada. Deixem apenas a Row da linha 39 com dois childrens: o Padding da linha 43 e a Column da linha 59. Pode apagar as outras duas rows que estão como filhas.

2022-03-18 21:25 UTC, VitorLamego commented on lib/components/EstateCard/estate_text.dart
> +class _EstateTextState extends State<EstateText> {
Não vejo necessidade em componentizar um widget de texto apenas. Eu entendi a ideia do porquê fizeram isso, mas acredito que um componente só para isso seja demais.
Uma ideia do que podem fazer é criar uma variável dentro da pasta Utils ( pessoal do cadastro criou ) para armazenar esse Text Style, algo como:
```suggestion
static final TextStyle estateTextStyle = TextStyle(
    color: Colors.black,
    fontSize: 20,
    fontFamily: 'Roboto-Regular',
  );
```

2022-03-18 21:29 UTC, VitorLamego commented on lib/components/EstateCard/estate_card.dart
> +class EstateCard extends StatefulWidget {
Não precisa ser Stateful, o card não possui mudança em seu estado.

2022-03-18 21:30 UTC, VitorLamego commented on lib/components/PendencyCard/pendency_card.dart
> +      child: Center(
Esse Center não é necessário.

2022-03-18 21:32 UTC, VitorLamego commented on pubspec.yaml
> +  #   - images/a_dot_ham.jpeg
Apagar esses comentários

2022-03-18 21:34 UTC, VitorLamego requested changes
Pessoal, parabéns pelo trabalho desenvolvido, as telas atenderam muito bem ao protótipo. Deixei alguns comentários para melhorias e mudanças em relação ao código. Assim que corrigidas eu aprovo o PR.

2022-03-20 13:14 UTC, VitorLamego approved these changes
Parabéns galera !! Bom trabalho.

2022-03-20 13:14 UTC, merged