Telas de Cadastro
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Mobile pull request #6
Opened 2022-03-15 18:14 UTC by oEduardoAfonso

# Descrição
Foram criadas as telas de cadastro de produtor e de técnico e a integração das mesmas com o backend.

# Está concertando alguma issue aberta ?
[#110](https://github.com/UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs/issues/110)

# Tarefas realizadas
- Criação da tela de cadastro de técnico
- Criação da tela de cadastro de produtor
- Feita a validação de todos os campos
- Feita a integração com backend

# Observações 
- Para alternar entre as telas é necessário comentar ou descomentar as linhas 35 ou 36 do arquivo "lib/main.dart"
- As requisições são feitas para o backend local, então é necessário rodá-lo antes de tentar concluir o cadastro

2022-03-26 15:19 UTC, brenno-silva requested changes
Bom trabalho pessoal, só precisa de alguns ajustes

2022-03-26 15:19 UTC, brenno-silva commented on lib/pages/register/technician_register/technician_register_page.dart
> +            SizedBox(height: 20),
Realmente precisa dos `SizedBox(height: 20)`? Testando aqui não mudou nada na página

2022-03-26 15:19 UTC, brenno-silva commented on lib/pages/select_account/select_account.dart
> +  void goToRegisterPage() {}
As `void goToTechnicianPage() {}` e ` void goToRegisterPage() {}` não estão fazendo nada

2022-03-26 15:19 UTC, brenno-silva commented on lib/pages/register/technician_register/technician_register_page.dart
> +      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
Esse `ScaffoldMessenger` poderia ser um componete da pasta register, já que nas 4 vezes que é utilizado só muda o texto

2022-03-26 15:19 UTC, brenno-silva commented on lib/utils/main.dart
> +class Utils {
Passar dados desse arquivo para o `utils.dart`

2022-03-26 15:19 UTC, brenno-silva commented on lib/pages/register/main.dart
> +class ProducerRegisterPage extends StatefulWidget {
Esse arquivo está está duplicando o `producer_register_page.dart`

2022-03-26 15:19 UTC, brenno-silva commented on lib/pages/select_account/select_account.dart
> +                    return ProducerRegisterPage();
Está redirecionando para o arquivo `main.dart` em vez do `producer_register_page.dart`

2022-03-26 15:19 UTC, brenno-silva commented on lib/pages/register/producer_register/producer_register_page.dart
> +                  Center(
Precisa de um navigate para a página de login ao clicar em "Cancelar"

2022-03-26 15:19 UTC, brenno-silva commented on lib/pages/register/technician_register/technician_register_page.dart
> +            Center(
Precisa de um navigate para a página de login ao clicar em "Cancelar"

2022-03-26 15:19 UTC, brenno-silva commented on lib/pages/register/producer_register/producer_register_page.dart
> +      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
Esse ScaffoldMessenger poderia ser um componete da pasta register, já que nas 4 vezes que é utilizado só muda o texto

2022-03-30 17:26 UTC, brenno-silva requested changes

2022-03-30 17:26 UTC, brenno-silva commented on lib/components/BaseAuthentication/main.dart
> +
Alterar nome do arquivo e colocar na raíz da pasta `components` como foi combinando

2022-03-30 17:26 UTC, brenno-silva commented on lib/components/TextBlueButton/main.dart
> +
Alterar nome do arquivo e colocar na raíz da pasta `components` como foi combinando

2022-03-30 17:26 UTC, brenno-silva commented on lib/components/UnderlineButton/main.dart
> +
Alterar nome do arquivo e colocar na raíz da pasta `components` como foi combinando

2022-03-30 17:26 UTC, brenno-silva commented on lib/components/BasicComponents.dart
> +
Alterar nome do arquivo para ficar em snake_case

2022-03-30 17:26 UTC, brenno-silva commented on lib/pages/register/producer_register/producer_register_page.dart
> +    final response = await DioClient().post('api/produtor/', {
Utilizar a estrutura similar a página de login com a controller

2022-03-30 17:26 UTC, brenno-silva commented on lib/pages/register/technician_register/technician_register_page.dart
> +    final response = await DioClient().post('api/tecnico/', {
Utilizar a estrutura da página de login com a controller

2022-03-30 17:26 UTC, brenno-silva commented on lib/services/http_client.dart
> +abstract class IHttpClient {
Arquivo não está sendo utilizado

2022-03-31 15:01 UTC, PauloAbiAcl requested changes
No geral foi um excelente trabalho, deixando algumas pequenas sugestões para alteração. Fica como alerta que na tela de login ao errar a requisição, ocorre um erro que não consegui identificar, importante identificar e corrigir,

2022-03-31 15:01 UTC, PauloAbiAcl commented on lib/utils/utils.dart
>    static Dio dio =
Como já temos uma instancia do Dio em dio.dart, acredito que não é necessário a existência dessa.

2022-03-31 15:01 UTC, PauloAbiAcl commented on lib/components/text_blue_button.dart
> +      height: 60,
Evitar usar tamanhos definidos como constante, optar por usar a MediaQuery class.

2022-03-31 15:01 UTC, PauloAbiAcl commented on lib/components/loading.dart
> +          child: Text(
O texto deve ser variável com a página ou ser escrito de forma mais genérica, como por exemplo: "Processando" ou "Carregando"

2022-03-31 15:01 UTC, PauloAbiAcl commented on lib/services/dio.dart
> +      baseUrl: 'http://0.0.0.0:8000/',
Adicionar a baseUrl do heroku, já que temos o deploy: https://ccd-backend.herokuapp.com/api/

2022-03-31 15:01 UTC, PauloAbiAcl commented on lib/services/register/register_service.dart
> +    Response response = await DioClient.dioClient.post('api/tecnico/', {
Padronizar a questão do endpoint tirando o 'api/' (nesse caso ficaria 'tecnico/'), já que em todos vamos usar a mesma rota colocamos direto na baseUrl.

2022-03-31 19:02 UTC, PauloAbiAcl approved these changes
Tudo certo!

2022-03-31 21:08 UTC, brenno-silva approved these changes

2022-03-31 21:58 UTC, merged