116 tela tipo conta
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Mobile pull request #8
Opened 2022-03-16 15:54 UTC by vital14

# Descrição
Criação da tela de escolha de conta

# Está concertando alguma issue aberta ?
#116

# Tarefas realizadas
- Criação da tela

# Observações 
-Ainda falta gerenciar corretamente o fluxo da tela
-Para vizualizar a tela trocar a home da main para select_account

2022-03-16 16:48 UTC, CarlosFiuza requested changes
Notei que as cores nos botões estão diferentes do protótipo.
Essa tela vai ser apresentada assim que o usuário clicar em "Cadastrar" na tela de login certo?
É que não vi um navigator.push na tela de login, mas acredito que é porque você está esperando o merge da tela de login.

2022-03-16 16:48 UTC, CarlosFiuza commented on lib/pages/select_account/select_account.dart
> +                            style: TextStyle(fontSize: 20),
Seguindo o protótipo a cor aqui deveria ser: 
```
Color(0XFF03045E)
```

2022-03-16 16:48 UTC, CarlosFiuza commented on lib/pages/select_account/select_account.dart
> +                          color: Colors.black,
Seguindo o protótipo a cor aqui deveria ser: 
```
Color(0XFF03045E)
```

2022-03-16 16:48 UTC, CarlosFiuza commented on lib/pages/select_account/select_account.dart
> +                            color: Colors.black,
Seguindo o protótipo a cor aqui deveria ser: 
```
Color(0XFF03045E)
```

2022-03-16 16:48 UTC, CarlosFiuza commented on lib/pages/select_account/select_account.dart
> +                            color: Colors.black,
Seguindo o protótipo a cor aqui deveria ser: 
```
Color(0XFF03045E)
```

2022-03-16 16:48 UTC, CarlosFiuza commented on lib/pages/select_account/select_account.dart
> +                          color: Colors.black,
Seguindo o protótipo a cor aqui deveria ser: 
```
Color(0XFF03045E)
```

2022-03-16 16:48 UTC, CarlosFiuza commented on lib/pages/select_account/select_account.dart
> +                            style: TextStyle(fontSize: 20),
Seguindo o protótipo a cor aqui deveria ser: 
```
Color(0XFF03045E)
```

2022-03-18 21:49 UTC, VitorLamego requested changes
Fazer correções do lint.

Realizar alterações comentadas, além de adicionar na página de login a navegação para essa página após apertar em "Cadastro". Parabéns pelo trabalho.

2022-03-18 21:49 UTC, VitorLamego commented on lib/pages/select_account/select_account.dart
> +                padding: EdgeInsets.only(top: 40, bottom: 150),
Colocar esse padding em medidas responsivas para evitar overflow em aparelhos pequenos.

2022-03-18 21:49 UTC, VitorLamego commented on lib/pages/select_account/select_account.dart
> +              margin: EdgeInsets.symmetric(vertical: 30),
Colocar em medidas responsivas.

2022-03-18 21:49 UTC, VitorLamego commented on lib/pages/select_account/select_account.dart
> +                          height: 35,
o Height seria bom estar em medida responsiva

2022-03-18 21:49 UTC, VitorLamego commented on lib/pages/select_account/select_account.dart
> +              margin: EdgeInsets.symmetric(vertical: 70),
Medida responsiva

2022-03-18 21:49 UTC, VitorLamego commented on lib/pages/select_account/select_account.dart
> +                          height: 35,
Medida responsiva

2022-03-18 21:49 UTC, VitorLamego commented on lib/pages/select_account/select_account.dart
> +              margin: EdgeInsets.only(top: 60),
Medida responsiva

2022-03-18 21:49 UTC, VitorLamego commented on lib/pages/select_account/select_account.dart
> +                            "PRODUTOR",
Não está centralizado como no texto "Técnico".

2022-03-18 21:49 UTC, VitorLamego commented on lib/pages/select_account/select_account.dart
> +class SelectTypePage extends StatelessWidget {
Mantém o nome da classe padronizada com o nome do arquivo, sugiro colocoar SelectAccount.

2022-03-22 00:05 UTC, VitorLamego approved these changes
Parabéns pelo trabalho!

2022-03-22 13:10 UTC, CarlosFiuza approved these changes
Parabéns!!

2022-03-22 22:31 UTC, merged