Criando componente global topbar
UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_Mobile pull request #9
Opened 2022-03-31 22:41 UTC by CarlosFiuza

Criação do componente global topbar com botões de voltar, editar e historico, sendo os dois últimos opcionais

2022-04-01 02:17 UTC, oEduardoAfonso requested changes
Ótimo trabalho Carlos, ideia muito boa de criar este componente.

Só precisa mudar a espessura da fonte que ficou um pouco mais grossa que o protótipo.

2022-04-01 02:17 UTC, oEduardoAfonso commented on lib/components/topbar_arrow_back.dart
> +          fontSize: 22,
Colocar também o peso da fonte ```fontWeight: FontWeight.normal,```

2022-04-01 16:56 UTC, brenno-silva requested changes
Muito bom

2022-04-01 16:56 UTC, brenno-silva commented on lib/components/topbar_arrow_back.dart
> +  final Size topbarHeight;
Esse tamanho poderia ser fixo dentro do próprio component

2022-04-01 18:24 UTC, CarlosFiuza commented on lib/components/topbar_arrow_back.dart
> +  final Size topbarHeight;
Pra usar um tamanho já definido dentro da classe TopbarArrowBack tem essas opções:
- Passar o BuildContext no construtor e tirar o Size dele.
- Passar o Size no construtor (semelhante ao que é feito agora).

Tentei colocar um valor fixo no construtor mas pra isso precisaria do context, que só aparece na função Widget build.

2022-04-01 20:39 UTC, oEduardoAfonso approved these changes
Show!! Ótimo trabalho! :fire:

2022-04-02 12:14 UTC, brenno-silva approved these changes

2022-04-03 04:39 UTC, merged